const translations = {
    en: {
        bio: "Solo Quest Modder And Game Maker",
        moddedApks: "Modded Apks",
        tagDiscord: "FREE GET BY DISCORD",
        discordCommunity: "Discord Community",
        tvMenuLib: "TvMenu Lib",
        tagFree: "FREE",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "PAID/GET BY DISCORD",
        moddedGtag: "Modded Gtag By Tvman",
        faqTitle: "Frequently Asked Questions",
        creditsTitle: "Credits",
        updates: "Updates",
        online: "Online",
        hubOnline: "Hub: Online",
        faqDesc: "Got questions about mods, menus, or releases? Find quick answers to common questions below!",
        q1Name: "Q: How do I download/get the modded APKs?",
        q1Val: "A: All free modded APKs and project files are distributed directly through our Discord community server. Join the Discord to access the download channels.",
        q2Name: "Q: Is TvMenu Lib free to use?",
        q2Val: "A: Yes! TvMenu Lib is completely free and intended for modding Gorilla Tag copies and fan games. Check the library tab for instructions.",
        q3Name: "Q: When is TvMenuPCVR releasing?",
        q3Val: "A: TvMenuPCVR is currently untested and coming soon. Keep an eye on the Discord announcements channel for release dates and testing info!",
        q4Name: "Q: Who do I contact if I need support?",
        q4Val: "A: You can reach out via email at TvmanMods@proton.me or open a support ticket inside our Discord server.",
        creditsText: "Credits to StripesVr for making the first hub!"
    },
    es: {
        bio: "Modder y Creador de Juegos Solo de Quest",
        moddedApks: "APKs Modificados",
        tagDiscord: "GRATIS OBTENER POR DISCORD",
        discordCommunity: "Comunidad de Discord",
        tvMenuLib: "TvMenu Lib",
        tagFree: "GRATIS",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "PAGO / OBTENER POR DISCORD",
        moddedGtag: "Gtag Modificado por Tvman",
        faqTitle: "Preguntas Frecuentes",
        creditsTitle: "Créditos",
        updates: "Actualizaciones",
        online: "En línea",
        hubOnline: "Hub: En línea",
        faqDesc: "¿Tienes dudas sobre mods, menús o lanzamientos? ¡Encuentra respuestas rápidas abajo!",
        q1Name: "¿Cómo descargo/consigo los APKs modificados?",
        q1Val: "Todos los APKs gratis se distribuyen en nuestro servidor de Discord. Únete para acceder a los canales de descarga.",
        q2Name: "¿Es TvMenu Lib gratis de usar?",
        q2Val: "¡Sí! TvMenu Lib es completamente gratis y sirve para modpear copias de Gorilla Tag y juegos de fans.",
        q3Name: "¿Cuándo se lanza TvMenuPCVR?",
        q3Val: "TvMenuPCVR aún no está probado y llegará pronto. ¡Atento a los anuncios de Discord!",
        q4Name: "¿Con quién contacto si necesito soporte?",
        q4Val: "Puedes escribirnos a TvmanMods@proton.me o abrir un ticket de soporte en Discord.",
        creditsText: "¡Créditos a StripesVr por hacer el primer hub!"
    },
    fr: {
        bio: "Moddeur Solo Quest et Créateur de Jeux",
        moddedApks: "APK Moddés",
        tagDiscord: "GRATUIT VIA DISCORD",
        discordCommunity: "Communauté Discord",
        tvMenuLib: "TvMenu Lib",
        tagFree: "GRATUIT",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "PAYANT / VIA DISCORD",
        moddedGtag: "Gtag Moddé par Tvman",
        faqTitle: "Foire Aux Questions",
        creditsTitle: "Crédits",
        updates: "Mises à jour",
        online: "En ligne",
        hubOnline: "Hub : En ligne",
        faqDesc: "Des questions sur les mods ou les sorties ? Trouvez des réponses rapides ci-dessous !",
        q1Name: "Comment télécharger les APK moddés ?",
        q1Val: "Tous les APK gratuits sont distribués sur notre serveur Discord. Rejoignez-le pour les salons de téléchargement.",
        q2Name: "Est-ce que TvMenu Lib est gratuit ?",
        q2Val: "Oui ! TvMenu Lib est totalement gratuit et sert à modder les copies de Gorilla Tag et jeux de fans.",
        q3Name: "Quand sortira TvMenuPCVR ?",
        q3Val: "TvMenuPCVR arrive bientôt. Surveillez les annonces sur le Discord !",
        q4Name: "Qui contacter pour du support ?",
        q4Val: "Contactez-nous par email à TvmanMods@proton.me ou ouvrez un ticket sur Discord.",
        creditsText: "Crédits à StripesVr pour avoir fait le premier hub !"
    },
    de: {
        bio: "Solo Quest Modder und Spieleentwickler",
        moddedApks: "Modifizierte APKs",
        tagDiscord: "KOSTENLOS ÜBER DISCORD",
        discordCommunity: "Discord-Community",
        tvMenuLib: "TvMenu Lib",
        tagFree: "KOSTENLOS",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "BEZAHLT / ÜBER DISCORD",
        moddedGtag: "Modifiziertes Gtag von Tvman",
        faqTitle: "Häufig gestellte Fragen",
        creditsTitle: "Mitwirkende",
        updates: "Updates",
        online: "Online",
        hubOnline: "Hub: Online",
        faqDesc: "Fragen zu Mods oder Releases? Hier gibt es schnelle Antworten!",
        q1Name: "Wie lade ich die modifizierten APKs herunter?",
        q1Val: "Alle kostenlosen APKs werden über unseren Discord-Server bereitgestellt. Trete dem Server bei.",
        q2Name: "Ist TvMenu Lib kostenlos?",
        q2Val: "Ja! TvMenu Lib ist völlig kostenlos und für das Modden von Gorilla Tag Kopien und Fangames gedacht.",
        q3Name: "Wann erscheint TvMenuPCVR?",
        q3Val: "TvMenuPCVR ist bald da. Behalte die Discord-Ankündigungen im Auge!",
        q4Name: "An wen wende ich mich bei Support-Fragen?",
        q4Val: "Schreibe eine E-Mail an TvmanMods@proton.me oder öffne ein Ticket auf Discord.",
        creditsText: "Credits an StripesVr für die Erstellung des ersten Hubs!"
    },
    it: {
        bio: "Modder di Quest Solitario e Creatore di Giochi",
        moddedApks: "APK Moddati",
        tagDiscord: "GRATIS TRAMITE DISCORD",
        discordCommunity: "Community Discord",
        tvMenuLib: "TvMenu Lib",
        tagFree: "GRATIS",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "PAGATO / TRAMITE DISCORD",
        moddedGtag: "Gtag Moddato da Tvman",
        faqTitle: "Domande Frequenti",
        creditsTitle: "Riconoscimenti",
        updates: "Aggiornamenti",
        online: "Online",
        hubOnline: "Hub: Online",
        faqDesc: "Hai domande su mod o rilasci? Trova risposte rapide qui sotto!",
        q1Name: "Come scarico gli APK moddati?",
        q1Val: "Tutti gli APK gratuiti sono distribuiti sul nostro server Discord. Unisciti per accedere ai download.",
        q2Name: "TvMenu Lib è gratis?",
        q2Val: "Sì! TvMenu Lib è completamente gratuito ed è pensato per moddare copie e fan game di Gorilla Tag.",
        q3Name: "Quando esce TvMenuPCVR?",
        q3Val: "TvMenuPCVR arriverà presto. Tieni d'occhio gli annunci su Discord!",
        q4Name: "A chi posso chiedere supporto?",
        q4Val: "Scrivi a TvmanMods@proton.me o apri un ticket nel nostro server Discord.",
        creditsText: "Crediti a StripesVr per aver creato il primo hub!"
    },
    pt: {
        bio: "Modder Solo de Quest e Criador de Jogos",
        moddedApks: "APKs Modificados",
        tagDiscord: "GRÁTIS VIA DISCORD",
        discordCommunity: "Comunidade Discord",
        tvMenuLib: "TvMenu Lib",
        tagFree: "GRÁTIS",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "PAGO / VIA DISCORD",
        moddedGtag: "Gtag Modificado por Tvman",
        faqTitle: "Perguntas Frequentes",
        creditsTitle: "Créditos",
        updates: "Atualizações",
        online: "Online",
        hubOnline: "Hub: Online",
        faqDesc: "Tem dúvidas sobre mods ou lançamentos? Encontre respostas rápidas abaixo!",
        q1Name: "Como baixar os APKs modificados?",
        q1Val: "Todos os APKs gratuitos são distribuídos no nosso servidor do Discord. Entre para acessar os canais.",
        q2Name: "O TvMenu Lib é gratuito?",
        q2Val: "Sim! O TvMenu Lib é totalmente gratuito e serve para moddar cópias e fan games de Gorilla Tag.",
        q3Name: "Quando o TvMenuPCVR será lançado?",
        q3Val: "O TvMenuPCVR será lançado em breve. Fique de olho nos anúncios do Discord!",
        q4Name: "Quem devo contatar para suporte?",
        q4Val: "Envie um e-mail para TvmanMods@proton.me ou abra um ticket no nosso Discord.",
        creditsText: "Créditos a StripesVr por fazer o primeiro hub!"
    },
    ru: {
        bio: "Соло Квест Моддер и Разработчик Игр",
        moddedApks: "Мод. APK",
        tagDiscord: "БЕСПЛАТНО ЧЕРЕЗ DISCORD",
        discordCommunity: "Discord Сообщество",
        tvMenuLib: "TvMenu Lib",
        tagFree: "БЕСПЛАТНО",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "ПЛАТНО / ЧЕРЕЗ DISCORD",
        moddedGtag: "Мод. Gtag от Tvman",
        faqTitle: "Часто задаваемые вопросы",
        creditsTitle: "Благодарности",
        updates: "Обновления",
        online: "В сети",
        hubOnline: "Хаб: В сети",
        faqDesc: "Есть вопросы по модам? Найдите ответы ниже!",
        q1Name: "Как скачать модифицированные APK?",
        q1Val: "Все бесплатные APK распространяются через наш сервер Discord.",
        q2Name: "Бесплатен ли TvMenu Lib?",
        q2Val: "Да! TvMenu Lib полностью бесплатен для создания модов на копии Gorilla Tag и фан-игры.",
        q3Name: "Когда выйдет TvMenuPCVR?",
        q3Val: "Скоро выйдет. Следите за анонсами в Discord!",
        q4Name: "Куда писать по поводу поддержки?",
        q4Val: "Напишите на почту TvmanMods@proton.me или откройте тикет в Discord.",
        creditsText: "Спасибо StripesVr за создание первого хаба!"
    },
    ja: {
        bio: "ソロクエストモッダー兼ゲームクリエイター",
        moddedApks: "改造版APK",
        tagDiscord: "Discordで無料取得",
        discordCommunity: "Discordコミュニティ",
        tvMenuLib: "TvMenu Lib",
        tagFree: "無料",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "有料 / Discordで取得",
        moddedGtag: "Tvman製改造Gtag",
        faqTitle: "よくある質問",
        creditsTitle: "クレジット",
        updates: "アップデート",
        online: "オンライン",
        hubOnline: "ハブ: オンライン",
        faqDesc: "Modやリリースについての質問はこちらをご覧ください！",
        q1Name: "改造版APKのダウンロード方法は？",
        q1Val: "無料のAPKはDiscordサーバーで配布しています。参加して確認してください。",
        q2Name: "TvMenu Libは無料で使えますか？",
        q2Val: "はい！完全無料でGorilla Tagのコピーやファンゲームのモディングに使えます。",
        q3Name: "TvMenuPCVRのリリース日は？",
        q3Val: "近日公開予定です。Discordのアナウンスをご確認ください！",
        q4Name: "サポートの問い合わせ先は？",
        q4Val: "TvmanMods@proton.meまでメールするか、Discordでチケットを開いてください。",
        creditsText: "最初のハブを作成したStripesVrに感謝します！"
    },
    ko: {
        bio: "솔로 퀘스트 모더 및 게임 제작자",
        moddedApks: "모드된 APK",
        tagDiscord: "디스코드에서 무료 받기",
        discordCommunity: "디스코드 커뮤니티",
        tvMenuLib: "TvMenu Lib",
        tagFree: "무료",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "유료 / 디스코드에서 받기",
        moddedGtag: "Tv만의 모드된 Gtag",
        faqTitle: "자주 묻는 질문",
        creditsTitle: "크레딧",
        updates: "업데이트",
        online: "온라인",
        hubOnline: "허브: 온라인",
        faqDesc: "모드나 배포에 관한 질문이 있으신가요? 아래에서 답변을 확인하세요!",
        q1Name: "모드된 APK는 어떻게 다운로드하나요?",
        q1Val: "모든 무료 APK는 디스코드 커뮤니티 서버를 통해 배포됩니다.",
        q2Name: "TvMenu Lib는 무료인가요?",
        q2Val: "네! TvMenu Lib는 고릴라 태그 복사본 및 팬 게임 모딩을 위해 완전히 무료로 제공됩니다.",
        q3Name: "TvMenuPCVR은 언제 출시되나요?",
        q3Val: "곧 출시될 예정입니다. 디스코드 공지를 확인하세요!",
        q4Name: "지원을 받으려면 누구에게 연락해야 하나요?",
        q4Val: "TvmanMods@proton.me로 이메일을 보내거나 디스코드에서 티켓을 여세요.",
        creditsText: "첫 번째 허브를 만들어준 StripesVr님께 크레딧을 보냅니다!"
    },
    zh: {
        bio: "独立 Quest Mod 制作人与游戏制作者",
        moddedApks: "修改版 APK",
        tagDiscord: "通过 Discord 免费获取",
        discordCommunity: "Discord 社区",
        tvMenuLib: "TvMenu Lib",
        tagFree: "免费",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "付费 / 通过 Discord 获取",
        moddedGtag: "Tvman 的修改版 Gtag",
        faqTitle: "常见问题",
        creditsTitle: "鸣谢",
        updates: "更新日志",
        online: "在线",
        hubOnline: "Hub：在线",
        faqDesc: "对 Mod 或发布有疑问？在下方查看快速解答！",
        q1Name: "如何下载修改版 APK？",
        q1Val: "所有免费修改版 APK 和项目文件均通过我们的 Discord 社区服务器分发。",
        q2Name: "TvMenu Lib 是免费使用的吗？",
        q2Val: "是的！TvMenu Lib 完全免费，用于修改 Gorilla Tag 副本和粉丝游戏。",
        q3Name: "TvMenuPCVR 什么时候发布？",
        q3Val: "TvMenuPCVR 正在测试中，即将推出。请留意 Discord 公告！",
        q4Name: "如果需要支持，我该联系谁？",
        q4Val: "您可以发邮件至 TvmanMods@proton.me 或在 Discord 中开启工单。",
        creditsText: "感谢 StripesVr 制作了第一个 Hub！"
    },
    ar: {
        bio: "معدل كويست وصانع ألعاب فردي",
        moddedApks: "ملفات APK المعدلة",
        tagDiscord: "مجاني عبر ديسبورد",
        discordCommunity: "مجتمع ديسكورد",
        tvMenuLib: "TvMenu Lib",
        tagFree: "مجاني",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "مدفوع / عبر ديسكورد",
        moddedGtag: "Gtag معدل بواسطة Tvman",
        faqTitle: "الأسئلة الشائعة",
        creditsTitle: "التقديرات",
        updates: "التحديثات",
        online: "متصل",
        hubOnline: "المنصة: متصل",
        faqDesc: "هل لديك أسئلة حول التعديلات؟ اعثر على إجابات سريعة أدناه!",
        q1Name: "كيف أقوم بتنزيل ملفات APK المعدلة؟",
        q1Val: "يتم توزيع جميع ملفات APK المجانية مباشرة عبر خادم ديسكورد الخاص بنا.",
        q2Name: "هل TvMenu Lib مجاني للاستخدام؟",
        q2Val: "نعم! TvMenu Lib مجاني تماماً ومخصص لتعديل نسخ Gorilla Tag وألعاب الفان.",
        q3Name: "متى سيتم إطلاق TvMenuPCVR؟",
        q3Val: "قريباً جداً. تابع إعلانات ديسكورد لمعرفة التواريخ!",
        q4Name: "من أين أحصل على الدعم؟",
        q4Val: "يمكنك التواصل عبر البريد الإلكتروني TvmanMods@proton.me أو فتح تذكرة دعم.",
        creditsText: "شكراً لـ StripesVr لإنشاء المنصة الأولى!"
    },
    hi: {
        bio: "सोलो क्वेस्ट मॉडर और गेम मेकर",
        moddedApks: "मॉड किए गए APK",
        tagDiscord: "डिस्कॉर्ड के माध्यम से मुफ्त",
        discordCommunity: "डिस्कॉर्ड कम्युनिटी",
        tvMenuLib: "TvMenu Lib",
        tagFree: "मुफ्त",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "सशुल्क / डिस्कॉर्ड से प्राप्त करें",
        moddedGtag: "Tvman द्वारा मॉड किया गया Gtag",
        faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
        creditsTitle: "क्रेडिट्स",
        updates: "अपडेट्स",
        online: "ऑनलाइन",
        hubOnline: "हब: ऑनलाइन",
        faqDesc: "मॉड या रिलीज़ के बारे में प्रश्न हैं? नीचे त्वरित उत्तर पाएं!",
        q1Name: "मैं मॉड किए गए APK कैसे डाउनलोड करूं?",
        q1Val: "सभी मुफ्त मॉड APK हमारे डिस्कॉर्ड सर्वर के माध्यम से वितरित किए जाते हैं।",
        q2Name: "क्या TvMenu Lib उपयोग करने के लिए स्वतंत्र है?",
        q2Val: "हाँ! TvMenu Lib पूरी तरह से मुफ्त है और इसका उपयोग गॉरीला टैग की प्रतियों और फैन गेम्स को मॉड करने के लिए किया जाता है।",
        q3Name: "TvMenuPCVR कब रिलीज़ हो रहा है?",
        q3Val: "यह जल्द ही आ रहा है। डिस्कॉर्ड घोषणाओं पर नज़र रखें!",
        q4Name: "सहायता के लिए किससे संपर्क करें?",
        q4Val: "आप TvmanMods@proton.me पर ईमेल कर सकते हैं।",
        creditsText: "पहला हब बनाने के लिए StripesVr को क्रेडिट!"
    },
    tr: {
        bio: "Solo Quest Modcusu ve Oyun Yapımcısı",
        moddedApks: "Modlu APK'lar",
        tagDiscord: "DİSCORD İLE ÜCRETSİZ AL",
        discordCommunity: "Discord Topluluğu",
        tvMenuLib: "TvMenu Lib",
        tagFree: "ÜCRETSİZ",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "ÜCRETLİ / DİSCORD'DAN AL",
        moddedGtag: "Tvman Tarafından Modlu Gtag",
        faqTitle: "Sıkça Sorulan Sorular",
        creditsTitle: "Emeği Geçenler",
        updates: "Güncellemeler",
        online: "Çevrimiçi",
        hubOnline: "Hub: Çevrimiçi",
        faqDesc: "Modlar veya sürümler hakkında sorularınız mı var? Aşağıda hızlı yanıtlar bulun!",
        q1Name: "Modlu APK'ları nasıl indirebilirim?",
        q1Val: "Tüm ücretsiz modlu APK'lar doğrudan Discord topluluk sunucumuz üzerinden dağıtılmaktadır.",
        q2Name: "TvMenu Lib kullanımı ücretsiz mi?",
        q2Val: "Evet! TvMenu Lib tamamen ücretsizdir ve Gorilla Tag kopyaları ile hayran oyunlarını modlamak içindir.",
        q3Name: "TvMenuPCVR ne zaman çıkıyor?",
        q3Val: "TvMenuPCVR yakında çıkıyor. Discord duyurularını takip edin!",
        q4Name: "Destek için kiminle iletişime geçmeliyim?",
        q4Val: "TvmanMods@proton.me adresine e-posta atabilir veya bir destek talebi açabilirsiniz.",
        creditsText: "İlk hub'ı yaptığı için StripesVr'ye teşekkürler!"
    },
    nl: {
        bio: "Solo Quest Modder en Spelmaker",
        moddedApks: "Gemodde APK's",
        tagDiscord: "GRATIS VIA DISCORD",
        discordCommunity: "Discord Community",
        tvMenuLib: "TvMenu Lib",
        tagFree: "GRATIS",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "BETAALD / VIA DISCORD",
        moddedGtag: "Gemodde Gtag Door Tvman",
        faqTitle: "Veelgestelde Vragen",
        creditsTitle: "Credits",
        updates: "Updates",
        online: "Online",
        hubOnline: "Hub: Online",
        faqDesc: "Vragen over mods of releases? Vind hieronder snelle antwoorden!",
        q1Name: "Hoe download ik de gemodde APK's?",
        q1Val: "Alle gratis gemodde APK's worden verdeeld via onze Discord-communityserver.",
        q2Name: "Is TvMenu Lib gratis te gebruiken?",
        q2Val: "Ja! TvMenu Lib is volledig gratis en bedoeld voor het modden van Gorilla Tag kopieën en fangames.",
        q3Name: "Wanneer komt TvMenuPCVR uit?",
        q3Val: "TvMenuPCVR komt binnenkort uit. Houd de Discord-aankondigingen in de gaten!",
        q4Name: "Wie kan ik contacteren voor ondersteuning?",
        q4Val: "Je kunt mailen naar TvmanMods@proton.me of een ticket openen in Discord.",
        creditsText: "Credits aan StripesVr voor het maken van de eerste hub!"
    },
    pl: {
        bio: "Samodzielny Modder Quest i Twórca Gier",
        moddedApks: "Zmodowane APK",
        tagDiscord: "DARMOWE PRZEZ DISCORD",
        discordCommunity: "Społeczność Discord",
        tvMenuLib: "TvMenu Lib",
        tagFree: "DARMOWE",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "PŁATNE / PRZEZ DISCORD",
        moddedGtag: "Zmodowany Gtag od Tvmana",
        faqTitle: "Często Zadawane Pytania",
        creditsTitle: "Podziękowania",
        updates: "Aktualizacje",
        online: "Online",
        hubOnline: "Hub: Online",
        faqDesc: "Masz pytania dotyczące modów? Znajdź szybkie odpowiedzi poniżej!",
        q1Name: "Jak pobrać zmodowane APK?",
        q1Val: "Wszystkie darmowe pliki APK są dystrybuowane bezpośrednio przez nasz serwer Discord.",
        q2Name: "Czy TvMenu Lib jest darmowe?",
        q2Val: "Tak! TvMenu Lib jest całkowicie darmowe i służy do modowania kopii Gorilla Tag i gier fanowskich.",
        q3Name: "Kiedy wychodzi TvMenuPCVR?",
        q3Val: "TvMenuPCVR pojawi się wkrótce. Śledź ogłoszenia na Discordzie!",
        q4Name: "Z kim się skontaktować w sprawie wsparcia?",
        q4Val: "Możesz napisać na adres TvmanMods@proton.me lub otworzyć bilet na Discordzie.",
        creditsText: "Podziękowania dla StripesVr za stworzenie pierwszego huba!"
    },
    vi: {
        bio: "Lập trình viên & Modder Solo Quest",
        moddedApks: "APK Đã Mod",
        tagDiscord: "MIỄN PHÍ QUA DISCORD",
        discordCommunity: "Cộng đồng Discord",
        tvMenuLib: "TvMenu Lib",
        tagFree: "MIỄN PHÍ",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "TRẢ PHÍ / QUA DISCORD",
        moddedGtag: "Gtag Đã Mod Bởi Tvman",
        faqTitle: "Câu Hỏi Thường Gặp",
        creditsTitle: "Ghi Công",
        updates: "Cập Nhật",
        online: "Trực tuyến",
        hubOnline: "Hub: Trực tuyến",
        faqDesc: "Có thắc mắc về mod hoặc bản phát hành? Xem câu trả lời bên dưới!",
        q1Name: "Làm sao để tải APK đã mod?",
        q1Val: "Tất cả APK miễn phí được phân phối trực tiếp qua máy chủ Discord của chúng tôi.",
        q2Name: "TvMenu Lib có miễn phí không?",
        q2Val: "Có! TvMenu Lib hoàn toàn miễn phí và dùng để mod các bản copy Gorilla Tag và game fan.",
        q3Name: "Khi nào TvMenuPCVR ra mắt?",
        q3Val: "TvMenuPCVR sắp ra mắt. Hãy chú ý thông báo trên Discord!",
        q4Name: "Liên hệ ai nếu cần hỗ trợ?",
        q4Val: "Bạn có thể gửi email đến TvmanMods@proton.me hoặc mở vé hỗ trợ trên Discord.",
        creditsText: "Cảm ơn StripesVr đã tạo ra hub đầu tiên!"
    },
    th: {
        bio: "นัก mod และผู้สร้างเกม Solo Quest",
        moddedApks: "APK ที่ถูก Mod",
        tagDiscord: "ฟรีผ่าน DISCORD",
        discordCommunity: "คอมมูนิตี้ Discord",
        tvMenuLib: "TvMenu Lib",
        tagFree: "ฟรี",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "จ่ายเงิน / ผ่าน DISCORD",
        moddedGtag: "Gtag Mod โดย Tvman",
        faqTitle: "คำถามที่พบบ่อย",
        creditsTitle: "เครดิต",
        updates: "อัปเดต",
        online: "ออนไลน์",
        hubOnline: "Hub: ออนไลน์",
        faqDesc: "มีคำถามเกี่ยวกับ mod หรือการปล่อยตัวใช่ไหม? ดูคำตอบด้านล่างได้เลย!",
        q1Name: "ฉันจะดาวน์โหลด APK ที่ Mod แล้วได้อย่างไร?",
        q1Val: "APK ฟรีทั้งหมดจะแจกจ่ายผ่านทางเซิร์ฟเวอร์ Discord ของเรา",
        q2Name: "TvMenu Lib ใช้งานฟรีหรือไม่?",
        q2Val: "ใช่! TvMenu Lib ใช้งานได้ฟรีและมีไว้สำหรับ mod สำเนา Gorilla Tag และเกมแฟนเมด",
        q3Name: "TvMenuPCVR จะปล่อยตัวเมื่อไหร่?",
        q3Val: "TvMenuPCVR กำลังจะมาเร็วๆ นี้ ติดตามประกาศใน Discord ได้เลย!",
        q4Name: "ติดต่อใครหากต้องการความช่วยเหลือ?",
        q4Val: "คุณสามารถส่งอีเมลไปที่ TvmanMods@proton.me หรือเปิดตั๋วซัพพอร์ตใน Discord",
        creditsText: "เครดิตถึง StripesVr สำหรับการสร้าง Hub แรก!"
    },
    id: {
        bio: "Modder Solo Quest dan Pembuat Game",
        moddedApks: "APK Mod",
        tagDiscord: "GRATIS LEWAT DISCORD",
        discordCommunity: "Komunitas Discord",
        tvMenuLib: "TvMenu Lib",
        tagFree: "GRATIS",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "BERBAYAR / LEWAT DISCORD",
        moddedGtag: "Gtag Mod oleh Tvman",
        faqTitle: "Pertanyaan yang Sering Diajukan",
        creditsTitle: "Kredit",
        updates: "Pembaruan",
        online: "Online",
        hubOnline: "Hub: Online",
        faqDesc: "Punya pertanyaan tentang mod? Temukan jawaban cepat di bawah ini!",
        q1Name: "Bagaimana cara mendownload APK mod?",
        q1Val: "Semua APK mod gratis dibagikan langsung melalui server Discord kami.",
        q2Name: "Apakah TvMenu Lib gratis digunakan?",
        q2Val: "Ya! TvMenu Lib sepenuhnya gratis dan ditujukan untuk modding salinan Gorilla Tag dan game buatan fans.",
        q3Name: "Kapan TvMenuPCVR rilis?",
        q3Val: "TvMenuPCVR akan segera hadir. Pantau terus pengumuman Discord!",
        q4Name: "Siapa yang harus dihubungi untuk dukungan?",
        q4Val: "Anda dapat mengirim email ke TvmanMods@proton.me atau buka tiket di Discord.",
        creditsText: "Kredit untuk StripesVr karena membuat hub pertama!"
    },
    uk: {
        bio: "Соло Квест Моддер та Розробник Ігор",
        moddedApks: "Мод. APK",
        tagDiscord: "БЕЗКОШТОВНО ЧЕРЕЗ DISCORD",
        discordCommunity: "Discord Спільнота",
        tvMenuLib: "TvMenu Lib",
        tagFree: "БЕЗКОШТОВНО",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "ПЛАТНО / ЧЕРЕЗ DISCORD",
        moddedGtag: "Мод. Gtag від Tvman",
        faqTitle: "Часті запитання",
        creditsTitle: "Подяки",
        updates: "Оновлення",
        online: "В мережі",
        hubOnline: "Хаб: В мережі",
        faqDesc: "Маєте запитання щодо модів? Знайдіть швидкі відповіді нижче!",
        q1Name: "Як завантажити модифіковані APK?",
        q1Val: "Усі безкоштовні APK розповсюджуються через наш сервер Discord.",
        q2Name: "Чи безкоштовний TvMenu Lib?",
        q2Val: "Так! TvMenu Lib повністю безкоштовний і призначений для створення модів на копії Gorilla Tag та фан-ігри.",
        q3Name: "Коли вийде TvMenuPCVR?",
        q3Val: "TvMenuPCVR з'явиться незабаром. Стежте за оголошеннями в Discord!",
        q4Name: "До кого звертатися за підтримкою?",
        q4Val: "Напишіть на пошту TvmanMods@proton.me або відкрийте тікет у Discord.",
        creditsText: "Подяка StripesVr за створення першого хабу!"
    },
    sv: {
        bio: "Solo Quest-moddare och Spelmakare",
        moddedApks: "Moddade APKs",
        tagDiscord: "GRATIS VIA DISCORD",
        discordCommunity: "Discord-community",
        tvMenuLib: "TvMenu Lib",
        tagFree: "GRATIS",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "BETALD / VIA DISCORD",
        moddedGtag: "Moddad Gtag Av Tvman",
        faqTitle: "Vanliga Frågor",
        creditsTitle: "Credits",
        updates: "Uppdateringar",
        online: "Online",
        hubOnline: "Hub: Online",
        faqDesc: "Har du frågor om moddar? Hitta snabba svar nedan!",
        q1Name: "Hur laddar jag ner de moddade APK-filerna?",
        q1Val: "Alla gratis moddade APK-filer distribueras direkt via vår Discord-server.",
        q2Name: "Är TvMenu Lib gratis att använda?",
        q2Val: "Ja! TvMenu Lib är helt gratis och avsett för att modda Gorilla Tag-kopior och fangames.",
        q3Name: "När släpps TvMenuPCVR?",
        q3Val: "TvMenuPCVR kommer snart. Håll utkik efter Discord-meddelanden!",
        q4Name: "Vem kontaktar jag för support?",
        q4Val: "Du kan nå oss via e-post på TvmanMods@proton.me eller öppna ett ärende på Discord.",
        creditsText: "Credits till StripesVr för att ha gjort den första hubben!"
    },
    no: {
        bio: "Solo Quest-modder og Spillskaper",
        moddedApks: "Moddende APK-er",
        tagDiscord: "GRATIS VIA DISCORD",
        discordCommunity: "Discord-fellesskap",
        tvMenuLib: "TvMenu Lib",
        tagFree: "GRATIS",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "BETALT / VIA DISCORD",
        moddedGtag: "Moddet Gtag Av Tvman",
        faqTitle: "Ofte Stilte Spørsmål",
        creditsTitle: "Anerkjennelse",
        updates: "Oppdateringer",
        online: "Tilgjengelig",
        hubOnline: "Hub: Online",
        faqDesc: "Har du spørsmål om modder? Finn raske svar nedenfor!",
        q1Name: "Hvordan laster jeg ned de moddede APK-ene?",
        q1Val: "Alle gratis APK-er distribueres direkte via Discord-serveren vår.",
        q2Name: "Er TvMenu Lib gratis å bruke?",
        q2Val: "Ja! TvMenu Lib er helt gratis og ment for modding av Gorilla Tag-kopier og fangames.",
        q3Name: "Når kommer TvMenuPCVR ut?",
        q3Val: "TvMenuPCVR kommer snart. Følg med på Discord-kunngjøringer!",
        q4Name: "Hvem kontakter jeg for støtte?",
        q4Val: "Du kan sende e-post til TvmanMods@proton.me eller åpne en sak på Discord.",
        creditsText: "Credits til StripesVr for å ha laget den første huben!"
    },
    da: {
        bio: "Solo Quest Modder og Spilskaber",
        moddedApks: "Moddede APK'er",
        tagDiscord: "GRATIS VIA DISCORD",
        discordCommunity: "Discord Fællesskab",
        tvMenuLib: "TvMenu Lib",
        tagFree: "GRATIS",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "BETALT / VIA DISCORD",
        moddedGtag: "Moddet Gtag Af Tvman",
        faqTitle: "Ofte Stillede Spørgsmål",
        creditsTitle: "Kreditter",
        updates: "Opdateringer",
        online: "Online",
        hubOnline: "Hub: Online",
        faqDesc: "Har du spørgsmål om mods? Find hurtige svar herunder!",
        q1Name: "Hvordan downloader jeg de moddede APK'er?",
        q1Val: "Alle gratis moddede APK'er distribueres direkte via vores Discord-server.",
        q2Name: "Er TvMenu Lib gratis at bruge?",
        q2Val: "Ja! TvMenu Lib er helt gratis og beregnet til at modde Gorilla Tag-kopier og fangames.",
        q3Name: "Hvornår udkommer TvMenuPCVR?",
        q3Val: "TvMenuPCVR udkommer snart. Hold øje med Discord-meddelelser!",
        q4Name: "Hvem kontakter jeg for support?",
        q4Val: "Du kan kontakte os via e-mail på TvmanMods@proton.me eller åbne en billet på Discord.",
        creditsText: "Kreditter til StripesVr for at lave den første hub!"
    },
    fi: {
        bio: "Solo Quest -moddaaja ja Pelintekijä",
        moddedApks: "Modatut APK:t",
        tagDiscord: "ILMAISEKSI DISCORDISTA",
        discordCommunity: "Discord-yhteisö",
        tvMenuLib: "TvMenu Lib",
        tagFree: "ILMAINEN",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "MAKSULLINEN / DISCORDISTA",
        moddedGtag: "Tvmanin Modattu Gtag",
        faqTitle: "Usein Kysytyt Kysymykset",
        creditsTitle: "Tekijät",
        updates: "Päivitykset",
        online: "Paikalla",
        hubOnline: "Hub: Online",
        faqDesc: "Onko sinulla kysyttävää modeista? Löydä nopeat vastaukset alta!",
        q1Name: "Miten lataan modatut APK:t?",
        q1Val: "Kaikki ilmaiset modatut APK:t jaetaan suoraan Discord-palvelimemme kautta.",
        q2Name: "Onko TvMenu Lib ilmainen käyttää?",
        q2Val: "Kyllä! TvMenu Lib on täysin ilmainen ja tarkoitettu Gorilla Tag -kopioiden ja fangamien modaukseen.",
        q3Name: "Milloin TvMenuPCVR julkaistaan?",
        q3Val: "TvMenuPCVR julkaistaan pian. Pidä silmällä Discord-ilmoituksia!",
        q4Name: "Kehen otan yhteyttä tuen tarvessa?",
        q4Val: "Voit laittaa sähköpostia osoitteeseen TvmanMods@proton.me tai avata tukilipun Discordissa.",
        creditsText: "Kiitokset StripesVr:lle ensimmäisen hubin tekemisestä!"
    },
    el: {
        bio: "Solo Quest Modder και Δημιουργός Παιχνιδιών",
        moddedApks: "Modded APKs",
        tagDiscord: "ΔΩΡΕΑΝ ΜΕΣΩ DISCORD",
        discordCommunity: "Κοινότητα Discord",
        tvMenuLib: "TvMenu Lib",
        tagFree: "ΔΩΡΕΑΝ",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "ΕΠΙΘΕΤΟ / ΜΕΣΩ DISCORD",
        moddedGtag: "Modded Gtag Από Tvman",
        faqTitle: "Συχνές Ερωτήσεις",
        creditsTitle: "Συντελεστές",
        updates: "Ενημερώσεις",
        online: "Συνδεδεμένος",
        hubOnline: "Hub: Σε σύνδεση",
        faqDesc: "Έχετε ερωτήσεις σχετικά με τα mods; Βρείτε γρήγορες απαντήσεις παρακάτω!",
        q1Name: "Πώς κατεβάζω τα modded APKs;",
        q1Val: "Όλα τα δωρεάν modded APKs διανέμονται απευθείας μέσω του διακομιστή Discord μας.",
        q2Name: "Είναι το TvMenu Lib δωρεάν στη χρήση;",
        q2Val: "Ναι! Το TvMenu Lib είναι εντελώς δωρεάν για modding αντιγράφων Gorilla Tag και fangames.",
        q3Name: "Πότε κυκλοφορεί το TvMenuPCVR;",
        q3Val: "Το TvMenuPCVR έρχεται σύντομα. Μείνετε συντονισμένοι στο Discord!",
        q4Name: "Ποιον να επικοινωνήσω για υποστήριξη;",
        q4Val: "Μπορείτε να στείλετε email στο TvmanMods@proton.me ή να ανοίξετε ticket στο Discord.",
        creditsText: "Ευχαριστούμε τον StripesVr για τη δημιουργία του πρώτου hub!"
    },
    cs: {
        bio: "Samostatný Quest Modder a Vývojář Her",
        moddedApks: "Modované APK",
        tagDiscord: "ZDARMA PŘES DISCORD",
        discordCommunity: "Discord Komunita",
        tvMenuLib: "TvMenu Lib",
        tagFree: "ZDARMA",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "PLACENÉ / PŘES DISCORD",
        moddedGtag: "Modovaný Gtag od Tvmana",
        faqTitle: "Často Kladené Otázky",
        creditsTitle: "Zásluhy",
        updates: "Aktualizace",
        online: "Online",
        hubOnline: "Hub: Online",
        faqDesc: "Máte otázky ohledně modů? Nalezněte rychlé odpovědi níže!",
        q1Name: "Jak stáhnu modované APK?",
        q1Val: "Všechny bezplatné modované APK jsou distribuovány přímo přes náš Discord server.",
        q2Name: "Je TvMenu Lib zdarma k použití?",
        q2Val: "Ano! TvMenu Lib je zcela zdarma a slouží k modování kopií Gorilla Tag a fangames.",
        q3Name: "Kdy vychází TvMenuPCVR?",
        q3Val: "TvMenuPCVR brzy vyjde. Sledujte oznámení na Discordu!",
        q4Name: "Na koho se obrátit pro podporu?",
        q4Val: "Můžete napsat na e-mail TvmanMods@proton.me nebo otevřít ticket na Discordu.",
        creditsText: "Poděkování StripesVr za vytvoření prvního hubu!"
    },
    hu: {
        bio: "Solo Quest Modder és Játékfejlesztő",
        moddedApks: "Modolt APK-k",
        tagDiscord: "INGYEN DISCORDON KERESZTÜL",
        discordCommunity: "Discord Közösség",
        tvMenuLib: "TvMenu Lib",
        tagFree: "INGYENES",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "FIZETŐS / DISCORDON KÉRVE",
        moddedGtag: "Modolt Gtag Tvman-től",
        faqTitle: "Gyakran Ismételt Kérdések",
        creditsTitle: "Készítők",
        updates: "Frissítések",
        online: "Elérhető",
        hubOnline: "Hub: Online",
        faqDesc: "Kérdéseid vannak a modokról? Találj gyors válaszokat lent!",
        q1Name: "Hogyan tudom letölteni a modolt APK-kat?",
        q1Val: "Minden ingyenes modolt APK közvetlenül a Discord közösségi szerverünkön keresztül érhető el.",
        q2Name: "Ingyenes a TvMenu Lib használata?",
        q2Val: "Igen! A TvMenu Lib teljesen ingyenes és a Gorilla Tag másolatok és rajongói játékok moddolására szolgál.",
        q3Name: "Mikor jelenik meg a TvMenuPCVR?",
        q3Val: "A TvMenuPCVR hamarosan érkezik. Figyeld a Discord hirdetéseket!",
        q4Name: "Kit keressek támogatásért?",
        q4Val: "Írhatsz e-mailt a TvmanMods@proton.me címre, vagy nyithatsz egy jegyet a Discordon.",
        creditsText: "Köszönjük StripesVr-nek az első hub megalkotását!"
    },
    ro: {
        bio: "Modder Solo Quest și Creator de Jocuri",
        moddedApks: "APK-uri Modificate",
        tagDiscord: "GRATUIT PRIN DISCORD",
        discordCommunity: "Comunitatea Discord",
        tvMenuLib: "TvMenu Lib",
        tagFree: "GRATUIT",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "CĂUTAT / PRIN DISCORD",
        moddedGtag: "Gtag Modificat de Tvman",
        faqTitle: "Întrebări Frecvente",
        creditsTitle: "Credite",
        updates: "Actualizări",
        online: "Online",
        hubOnline: "Hub: Online",
        faqDesc: "Ai întrebări despre moduri? Găsește răspunsuri rapide mai jos!",
        q1Name: "Cum descarc APK-urile modificate?",
        q1Val: "Toate APK-urile gratuite sunt distribuite direct prin serverul nostru de Discord.",
        q2Name: "Este TvMenu Lib gratuit de utilizat?",
        q2Val: "Da! TvMenu Lib este complet gratuit și este destinat moddării copiilor Gorilla Tag și fan game-urilor.",
        q3Name: "Când se lansează TvMenuPCVR?",
        q3Val: "TvMenuPCVR vine în curând. Fii cu ochii pe anunțurile de pe Discord!",
        q4Name: "Pe cine contactez pentru suport?",
        q4Val: "Poți trimite un e-mail la TvmanMods@proton.me sau poți deschide un tichet pe Discord.",
        creditsText: "Credite lui StripesVr pentru crearea primului hub!"
    },
    sk: {
        bio: "Samostatný Quest Modder a Vývojár Hier",
        moddedApks: "Modované APK",
        tagDiscord: "ZADARMO CEZ DISCORD",
        discordCommunity: "Discord Komunita",
        tvMenuLib: "TvMenu Lib",
        tagFree: "ZADARMO",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "PLATENÉ / CEZ DISCORD",
        moddedGtag: "Modovaný Gtag od Tvmana",
        faqTitle: "Často Kladené Otázky",
        creditsTitle: "Zásluhy",
        updates: "Aktualizácie",
        online: "Online",
        hubOnline: "Hub: Online",
        faqDesc: "Máte otázky ohľadom modov? Nájdite rýchle odpovede nižšie!",
        q1Name: "Ako stiahnem modované APK?",
        q1Val: "Všetky bezplatné modované APK sú distribuované priamo cez náš Discord server.",
        q2Name: "Je TvMenu Lib zadarmo na použitie?",
        q2Val: "Áno! TvMenu Lib je úplne zadarmo a slúži na modovanie kópií Gorilla Tag a fanúšikovských hier.",
        q3Name: "Kedy vychádza TvMenuPCVR?",
        q3Val: "TvMenuPCVR čoskoro vyjde. Sledujte oznámenia na Discorde!",
        q4Name: "Na koho sa obrátiť o podporu?",
        q4Val: "Môžete napísať na e-mail TvmanMods@proton.me alebo otvoriť ticket na Discorde.",
        creditsText: "Poďakovanie StripesVr za vytvorenie prvého hubu!"
    },
    bg: {
        bio: "Соло Куест Модър и Създател на Игри",
        moddedApks: "Модифицирани APK",
        tagDiscord: "БЕЗПЛАТНО ПРЕЗ DISCORD",
        discordCommunity: "Discord Общност",
        tvMenuLib: "TvMenu Lib",
        tagFree: "БЕЗПЛАТНО",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "ПЛАТЕНО / ПРЕЗ DISCORD",
        moddedGtag: "Модифициран Gtag от Tvman",
        faqTitle: "Често Задавани Въпроси",
        creditsTitle: "Заслуги",
        updates: "Обновления",
        online: "На линия",
        hubOnline: "Хъб: На линия",
        faqDesc: "Имате ли въпроси относно модовете? Намерете бързи отговори по-долу!",
        q1Name: "Как да изтегля модифицираните APK?",
        q1Val: "Всички безплатни APK се разпространяват директно през нашия Discord сървър.",
        q2Name: "Безплатен ли е TvMenu Lib за използване?",
        q2Val: "Да! TvMenu Lib е напълно безплатен и е предназначен за модване на копия на Gorilla Tag и фен игри.",
        q3Name: "Кога излиза TvMenuPCVR?",
        q3Val: "TvMenuPCVR очаквайте скоро. Следете обявленията в Discord!",
        q4Name: "Към кого да се обърна за поддръжка?",
        q4Val: "Можете да пишете на имейл TvmanMods@proton.me или да отворите билет в Discord.",
        creditsText: "Благодарности на StripesVr за създаването на първия хъб!"
    },
    hr: {
        bio: "Solo Quest Modder i Tvorac Igara",
        moddedApks: "Modirani APK-ovi",
        tagDiscord: "BESPLATNO PUTEM DISCORDA",
        discordCommunity: "Discord Zajednica",
        tvMenuLib: "TvMenu Lib",
        tagFree: "BESPLATNO",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "PLAĆENO / PUTEM DISCORDA",
        moddedGtag: "Modirani Gtag od Tvmana",
        faqTitle: "Često Postavljana Pitanja",
        creditsTitle: "Zasluge",
        updates: "Ažuriranja",
        online: "Dostupan",
        hubOnline: "Hub: Online",
        faqDesc: "Imate pitanja o modovima? Pronađite brze odgovore u nastavku!",
        q1Name: "Kako preuzeti modirane APK-ove?",
        q1Val: "Svi besplatni APK-ovi distribuiraju se izravno putem našeg Discord poslužitelja.",
        q2Name: "Je li TvMenu Lib besplatan za korištenje?",
        q2Val: "Da! TvMenu Lib je potpuno besplatan za modiranje kopija Gorilla Taga i fangameova.",
        q3Name: "Kada izlazi TvMenuPCVR?",
        q3Val: "TvMenuPCVR stiže uskoro. Pratite obavijesti na Discordu!",
        q4Name: "Koga kontaktirati za podršku?",
        q4Val: "Možete poslati e-poruku na TvmanMods@proton.me ili otvoriti tiket na Discordu.",
        creditsText: "Zasluge StripesVru za izradu prvog huba!"
    },
    sr: {
        bio: "Соло Квест Моддер и Творац Игара",
        moddedApks: "Модовани APK-ови",
        tagDiscord: "БЕСПЛАТНО ПУТЕМ DISCORDA",
        discordCommunity: "Discord Заједница",
        tvMenuLib: "TvMenu Lib",
        tagFree: "БЕСПЛАТНО",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "ПЛАЋЕНО / ПУТЕМ DISCORDA",
        moddedGtag: "Модовани Gtag од Твмана",
        faqTitle: "Често Постављана Pитања",
        creditsTitle: "Заслуге",
        updates: "Ажурирања",
        online: "Онлајн",
        hubOnline: "Hub: Онлајн",
        faqDesc: "Имате ли питања у вези модова? Пронађите брзе одговоре испод!",
        q1Name: "Како да преузмем момоване APK-ове?",
        q1Val: "Сви бесплатни APK-ови се дистрибуирају директно преко нашег Discord сервера.",
        q2Name: "Да ли је TvMenu Lib бесплатан за коришћење?",
        q2Val: "Да! TvMenu Lib је потпуно бесплатан за модовање Gorilla Tag копија и фен игрица.",
        q3Name: "Када излази TvMenuPCVR?",
        q3Val: "TvMenuPCVR стиже ускоро. Пратите објаве на Discord-у!",
        q4Name: "Кога да контактирам за подршку?",
        q4Val: "Можете послати е-пошту на TvmanMods@proton.me или отворити тикет на Discord-у.",
        creditsText: "Заслуге за StripesVr за израду првог хаба!"
    },
    ms: {
        bio: "Modder Solo Quest dan Pembuat Permainan",
        moddedApks: "APK Mod",
        tagDiscord: "PERCUMA MELALUI DISCORD",
        discordCommunity: "Komuniti Discord",
        tvMenuLib: "TvMenu Lib",
        tagFree: "PERCUMA",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "BERBAYAR / MELALUI DISCORD",
        moddedGtag: "Gtag Mod oleh Tvman",
        faqTitle: "Soalan Lazim",
        creditsTitle: "Kredit",
        updates: "Kemaskini",
        online: "Dalam talian",
        hubOnline: "Hub: Dalam Talian",
        faqDesc: "Ada soalan mengenai mod? Cari jawapan pantas di bawah!",
        q1Name: "Bagaimana cara memuat turun APK mod?",
        q1Val: "Semua APK mod percuma diedarkan terus melalui pelayan komuniti Discord kami.",
        q2Name: "Adakah TvMenu Lib percuma digunakan?",
        q2Val: "Ya! TvMenu Lib adalah percuma sepenuhnya untuk modding salinan Gorilla Tag dan permainan peminat.",
        q3Name: "Bilakah TvMenuPCVR akan dilancarkan?",
        q3Val: "TvMenuPCVR akan datang tidak lama lagi. Perhatikan pengumuman Discord!",
        q4Name: "Siapa yang perlu dihubungi untuk sokongan?",
        q4Val: "Anda boleh e-mel ke TvmanMods@proton.me atau buka tiket sokongan di Discord.",
        creditsText: "Kredit kepada StripesVr kerana membuat hub pertama!"
    },
    tl: {
        bio: "Solo Quest Modder at Game Maker",
        moddedApks: "Modded APKs",
        tagDiscord: "LIBRE SA DISCORD",
        discordCommunity: "Komunidad sa Discord",
        tvMenuLib: "TvMenu Lib",
        tagFree: "LIBRE",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "MAY BAYAD / SA DISCORD",
        moddedGtag: "Modded Gtag Ni Tvman",
        faqTitle: "Mga Madalas Itanong",
        creditsTitle: "Mga Kredito",
        updates: "Mga Update",
        online: "Online",
        hubOnline: "Hub: Online",
        faqDesc: "May mga katanungan tungkol sa mga mod? Maghanap ng mga sagot sa ibaba!",
        q1Name: "Paano ko i-download ang mga modded APK?",
        q1Val: "Lahat ng libreng APK ay ipinamamahagi sa pamamagitan ng aming Discord server.",
        q2Name: "Libre bang gamitin ang TvMenu Lib?",
        q2Val: "Oo! Ang TvMenu Lib ay libre at nakalaan para sa pag-mod ng mga kopya ng Gorilla Tag at fan games.",
        q3Name: "Kailan lalabas ang TvMenuPCVR?",
        q3Val: "Malapit na ang TvMenuPCVR. Abangan ang mga anunsyo sa Discord!",
        q4Name: "Sino ang kokontakin para sa suporta?",
        q4Val: "Maaari kang mag-email sa TvmanMods@proton.me o magbukas ng ticket sa Discord.",
        creditsText: "Kredito kay StripesVr sa paggawa ng unang hub!"
    },
    fa: {
        bio: "ماد ساز انفرادی کوئست و بازیساز",
        moddedApks: "فایل‌های APK مود شده",
        tagDiscord: "رایگان از طریق دیسکورد",
        discordCommunity: "انجمن دیسکورد",
        tvMenuLib: "TvMenu Lib",
        tagFree: "رایگان",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "پولی / از طریق دیسکورد",
        moddedGtag: "گوریلا تگ مود شده توسط Tvman",
        faqTitle: "سوالات متداول",
        creditsTitle: "عوامل و سازندگان",
        updates: "به‌روزرسانی‌ها",
        online: "آنلاین",
        hubOnline: "هاب: آنلاین",
        faqDesc: "سوالی درباره مادها دارید؟ پاسخ‌های سریع را در ادامه بخوانید!",
        q1Name: "چگونه فایل‌های APK مود شده را دانلود کنم؟",
        q1Val: "تمامی فایل‌های رایگان مستقیماً از طریق سرور دیسکورد ما توزیع می‌شوند.",
        q2Name: "آیا TvMenu Lib رایگان است؟",
        q2Val: "بله! کتابخانه TvMenu Lib کاملاً رایگان است و برای ماد کردن نسخه‌های گوریلا تگ و بازی‌های طرفداری کاربرد دارد.",
        q3Name: "TvMenuPCVR چه زمانی عرضه می‌شود؟",
        q3Val: "به زودی عرضه خواهد شد. اطلاعیه‌های دیسکورد را دنبال کنید!",
        q4Name: "برای پشتیبانی با چه کسی تماس بگیرم؟",
        q4Val: "می‌توانید به ایمیل TvmanMods@proton.me پیام دهید یا در دیسکورد تیکت باز کنید.",
        creditsText: "تشکر از StripesVr برای ساخت اولین هاب!"
    },
    he: {
        bio: "מוודר קווסט יחיד ויוצר משחקים",
        moddedApks: "קובצי APK מותאמים",
        tagDiscord: "חינם דרך דיסקורד",
        discordCommunity: "קהילת דיסקורד",
        tvMenuLib: "TvMenu Lib",
        tagFree: "חינם",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "בתשלום / דרך דיסקורד",
        moddedGtag: "Gtag מותאם אישית מאת Tvman",
        faqTitle: "שאלות נפוצות",
        creditsTitle: "קרדיטים",
        updates: "עדכונים",
        online: "מחובר",
        hubOnline: "האב: מחובר",
        faqDesc: "יש לך שאלות על מודים? מצא תשובות מהירות למטה!",
        q1Name: "איך מורידים את ה-APKs המותאמים?",
        q1Val: "כל קובצי ה-APK החינמיים מופצים דרך שרת הדיסקורד שלנו.",
        q2Name: "האם TvMenu Lib חינמי לשימוש?",
        q2Val: "כן! TvMenu Lib חינמי לחלוטין ומיועד ליצירת מודים לעותקים של גורילה טאג ולמשחקי מעריצים.",
        q3Name: "מתי TvMenuPCVR יוצא?",
        q3Val: "TvMenuPCVR מגיע בקרוב מאוד. עקוב אחר ההודעות בדיסקורד!",
        q4Name: "למי פונים לתמיכה?",
        q4Val: "ניתן לשלוח אימייל לכתובת TvmanMods@proton.me או לפתוח כרטיס תמיכה בדיסקורד.",
        creditsText: "קרדיט ל-StripesVr על בניית ההאב הראשון!"
    },
    bn: {
        bio: "সলো কোয়েস্ট মডার এবং গেম মেকার",
        moddedApks: "মড করা APKs",
        tagDiscord: "ডিসকর্ডের মাধ্যমে ফ্রি",
        discordCommunity: "ডিসকর্ড কমিউনিটি",
        tvMenuLib: "TvMenu Lib",
        tagFree: "ফ্রি",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "পেইড / ডিসকর্ড থেকে নিন",
        moddedGtag: "Tvman দ্বারা মড করা Gtag",
        faqTitle: "সচরাচর জিজ্ঞাসিত প্রশ্নাবলী",
        creditsTitle: "স্বীকৃতি",
        updates: "আপডেট",
        online: "অনলাইন",
        hubOnline: "হাব: অনলাইন",
        faqDesc: "মড বা রিলিজ সম্পর্কে প্রশ্ন আছে? নিচে দ্রুত উত্তর খুঁজুন!",
        q1Name: "আমি কিভাবে মড করা APK গুলি ডাউনলোড করব?",
        q1Val: "সমস্ত ফ্রি মড করা APK আমাদের ডিসকর্ড সার্ভারের মাধ্যমে বিতরণ করা হয়।",
        q2Name: "TvMenu Lib কি ব্যবহারের জন্য বিনামূল্যে?",
        q2Val: "হ্যাঁ! TvMenu Lib সম্পূর্ণ বিনামূল্যে এবং গরিলা ট্যাগ কপি এবং ফ্যান গেম মড করার জন্য তৈরি।",
        q3Name: "TvMenuPCVR কবে রিলিজ হচ্ছে?",
        q3Val: "TvMenuPCVR খুব শীঘ্রই আসছে। ডিসকর্ড ঘোষণাগুলিতে নজর রাখুন!",
        q4Name: "সহায়তার জন্য কার সাথে যোগাযোগ করব?",
        q4Val: "আপনি TvmanMods@proton.me এ ইমেল করতে পারেন বা ডিসকর্ডে টিকিট খুলতে পারেন।",
        creditsText: "প্রথম হাব তৈরি করার জন্য StripesVr-কে ধন্যবাদ!"
    },
    ur: {
        bio: "سولو کویسٹ ماڈر اور گیم میکر",
        moddedApks: "موڈیفائید APKs",
        tagDiscord: "ڈسکارڈ کے ذریعے مفت",
        discordCommunity: "ڈسکارڈ کمیونٹی",
        tvMenuLib: "TvMenu Lib",
        tagFree: "مفت",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "پیڈ / ڈسکارڈ سے حاصل کریں",
        moddedGtag: "Tvman کا موڈیفائید Gtag",
        faqTitle: "اکثر پوچھے گئے سوالات",
        creditsTitle: "کریڈیٹس",
        updates: "اپ ڈیٹس",
        online: "آن لائن",
        hubOnline: "حب: آن لائن",
        faqDesc: "مڈز کے بارے میں سوالات ہیں؟ نیچے فوری جوابات تلاش کریں!",
        q1Name: "میں موڈیفائید APKs کیسے ڈاؤن لوڈ کروں؟",
        q1Val: "تمام مفت APKs ہمارے ڈسکارڈ سرور के ذریعے تقسیم کیے جاتے ہیں۔",
        q2Name: "کیا TvMenu Lib استعمال کرنے کے لیے مفت ہے؟",
        q2Val: "ہاں! TvMenu Lib مکمل طور پر مفت ہے اور گوریلا ٹیگ کی کاپیوں اور فین گیمز کو موڈ کرنے کے لیے ہے۔",
        q3Name: "TvMenuPCVR کب ریلیز ہو رہا ہے؟",
        q3Val: "TvMenuPCVR جلد آرہا ہے۔ ڈسکارڈ اعلانات پر نظر رکھیں!",
        q4Name: "سپورٹ کے لیے کس سے رابطہ کریں؟",
        q4Val: "آپ TvmanMods@proton.me پر ای میل کر سکتے ہیں یا ڈسکارڈ میں ٹکٹ کھول سکتے ہیں۔",
        creditsText: "پہلا حب بنانے کے لیے StripesVr کا شکریہ!"
    },
    mr: {
        bio: "सोलो क्वेस्ट मॉडर आणि गेम मेकर",
        moddedApks: "मॉड केलेले APK",
        tagDiscord: "डिस्कॉर्डद्वारे मोफत",
        discordCommunity: "डिस्कॉर्ड कम्युनिटी",
        tvMenuLib: "TvMenu Lib",
        tagFree: "मोफत",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "सशुल्क / डिस्कॉर्डवरून मिळवा",
        moddedGtag: "Tvman द्वारे मॉड केलेले Gtag",
        faqTitle: "सतत विचारले जाणारे प्रश्न",
        creditsTitle: "श्रेय",
        updates: "अपडेट्स",
        online: "ऑनलाइन",
        hubOnline: "हब: ऑनलाइन",
        faqDesc: "मॉड्सबद्दल प्रश्न आहेत? खाली उत्तरे शोधा!",
        q1Name: "मी मॉड केलेले APK कसे डाउनलोड करू?",
        q1Val: "सर्व मोफत APK आमच्या डिस्कॉर्ड सर्व्हरद्वारे वितरित केले जातात.",
        q2Name: "TvMenu Lib वापरण्यासाठी मोफत आहे का?",
        q2Val: "होय! TvMenu Lib पूर्णपणे मोफत आहे आणि गोरीला टॅग कॉपीज आणि फॅन गेम्स मॉड करण्यासाठी आहे.",
        q3Name: "TvMenuPCVR कधी रिलीज होत आहे?",
        q3Val: "TvMenuPCVR लवकरच येत आहे. डिस्कॉर्ड घोषणांवर लक्ष ठेवा!",
        q4Name: "मदतीसाठी कोणाशी संपर्क साधावा?",
        q4Val: "तुम्ही TvmanMods@proton.me वर ईमेल पाठवू शकता.",
        creditsText: "पहिले हब बनवल्याबद्दल StripesVr चे आभार!"
    },
    ta: {
        bio: "சோலோ குவெஸ்ட் மோடர் மற்றும் கேம் மேக்கர்",
        moddedApks: "மோட் செய்யப்பட்ட APKs",
        tagDiscord: "டிஸ்கார்ட் மூலம் இலவசம்",
        discordCommunity: "டிஸ்கார்ட் சமூகம்",
        tvMenuLib: "TvMenu Lib",
        tagFree: "இலவசம்",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "கட்டணம் / டிஸ்கார்ட் மூலம்",
        moddedGtag: "Tvman இன் மோட் செய்யப்பட்ட Gtag",
        faqTitle: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
        creditsTitle: "நன்றிகள்",
        updates: "புதுப்பிப்புகள்",
        online: "ஆன்லைன்",
        hubOnline: "ஹப்: ஆன்லைன்",
        faqDesc: "மோட்ஸ் பற்றிய கேள்விகள் உள்ளதா? கீழே விரைவான பதில்களைக் கண்டறியவும்!",
        q1Name: "மோட் செய்யப்பட்ட APK ஐ எவ்வாறு பதிவிறக்குவது?",
        q1Val: "அனைத்து இலவச APK க்களும் எங்கள் டிஸ்கார்ட் சர்வர் மூலம் பகிரப்படுகின்றன.",
        q2Name: "TvMenu Lib இலவசமாக பயன்படுத்தலாமா?",
        q2Val: "ஆம்! TvMenu Lib முற்றிலும் இலவசம் மற்றும் கோரில்லா டேக் நகல்கள் மற்றும் ஃபேன் கேம்களை மோட் செய்ய வடிவமைக்கப்பட்டுள்ளது.",
        q3Name: "TvMenuPCVR எப்போது வெளியிடப்படும்?",
        q3Val: "TvMenuPCVR விரைவில் வருகிறது. டிஸ்கார்ட் அறிவிப்புகளைப் பார்க்கவும்!",
        q4Name: "ஆதரவுக்கு யாரைத் தொடர்புகொள்வது?",
        q4Val: "TvmanMods@proton.me என்ற முகவரிക്ക് மின்னஞ்சல் அனுப்பலாம்.",
        creditsText: "முதல் ஹப்பை உருவாக்கிய StripesVr-க்கு நன்றிகள்!"
    },
    te: {
        bio: "సోలో క్వెస్ట్ మోడర్ మరియు గేమ్ మేకర్",
        moddedApks: "మోడ్ చేయబడిన APK లు",
        tagDiscord: "డిస్కార్డ్ ద్వారా ఉచితం",
        discordCommunity: "డిస్కార్డ్ సంఘం",
        tvMenuLib: "TvMenu Lib",
        tagFree: "ఉచితం",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "పెయిడ్ / డిస్కార్డ్ ద్వారా",
        moddedGtag: "Tvman ద్వారా మోడ్ చేయబడిన Gtag",
        faqTitle: "తరచుగా అడిగే ప్రశ్నలు",
        creditsTitle: "క్రెడిట్స్",
        updates: "అప్‌డేట్స్",
        online: "ఆన్‌లైన్",
        hubOnline: "హబ్: ఆన్‌లైన్",
        faqDesc: "మోడ్‌ల గురించి ప్రశ్నలు ఉన్నాయా? కింద త్వరిత సమాధానాలను కనుగొనండి!",
        q1Name: "మోడ్ చేసిన APK లను ఎలా డౌన్‌లోడ్ చేయాలి?",
        q1Val: "ఉచిత APK అన్నీ మా డిస్కార్డ్ సర్వర్ ద్వారా అందించబడతాయి.",
        q2Name: "TvMenu Lib ఉచితంగా ఉపయోగించవచ్చా?",
        q2Val: "అవును! TvMenu Lib పూర్తిగా ఉచితం మరియు గోరిల్లా ట్యాగ్ కాపీలు మరియు ఫ్యాన్ గేమ్‌లను మోడ్ చేయడానికి ఉద్దేశించబడింది.",
        q3Name: "TvMenuPCVR ఎప్పుడు విడుదలవుతుంది?",
        q3Val: "TvMenuPCVR త్వరలో వస్తుంది. డిస్కార్డ్ ప్రకటనలను గమనించండి!",
        q4Name: "మద్దతు కోసం ఎవరిని సంప్రదించాలి?",
        q4Val: "మీరు TvmanMods@proton.me కి ఇమెయిల్ చేయవచ్చు.",
        creditsText: "మొదటి హబ్‌ను సృష్టించినందుకు StripesVr కి ధన్యవాదాలు!"
    },
    sw: {
        bio: "Modder wa Solo Quest na Muundaji wa Michezo",
        moddedApks: "APK Zilizobadilishwa",
        tagDiscord: "BURE KUPITIA DISCORD",
        discordCommunity: "Jumuiya ya Discord",
        tvMenuLib: "TvMenu Lib",
        tagFree: "BURE",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "INALIPWA / KUPITIA DISCORD",
        moddedGtag: "Gtag Iliyobadilishwa na Tvman",
        faqTitle: "Maswali Yanayoulizwa Mara kwa Mara",
        creditsTitle: "Sifa na Shukrani",
        updates: "Sasisho",
        online: "Mtandaoni",
        hubOnline: "Hub: Mtandaoni",
        faqDesc: "Una maswali kuhusu mods? Pata majibu ya haraka hapa chini!",
        q1Name: "Ninafanyaje download APK zilizobadilishwa?",
        q1Val: "APK zote za bure zinasambazwa moja kwa moja kupitia seva yetu ya Discord.",
        q2Name: "Je, TvMenu Lib ni bure kutumia?",
        q2Val: "Ndiyo! TvMenu Lib ni bure kabisa na imekusudiwa kwa ajili ya modding nakala za Gorilla Tag na michezo ya mashabiki.",
        q3Name: "TvMenuPCVR inatoka lini?",
        q3Val: "TvMenuPCVR inakuja hivi karibuni. Angalia matangazo ya Discord!",
        q4Name: "Nani wa kumgusa kwa msaada?",
        q4Val: "Unaweza kutuma barua pepe kwa TvmanMods@proton.me au kufungua tiketi kwenye Discord.",
        creditsText: "Shukrani kwa StripesVr kwa kutengeneza hub ya kwanza!"
    }
};
